import turtle as t
t.shape('turtle')
def circle(r):
	for  i in range(360):
		t.forward(r)
		t.right(1)
t.right(180)
t.fillcolor("yellow")
t.begin_fill()
circle(2)
t.end_fill()
t.penup()
t.goto(-40,120)
t.pendown()
t.fillcolor("blue")
t.begin_fill()
circle(0.3)
t.end_fill()
t.penup()
t.goto(40,120)
t.pendown()
t.fillcolor("blue")
t.begin_fill()
circle(0.3)
t.end_fill()
t.penup()
t.goto(0,110)
t.pendown()
t.width(10)
t.left(90)
t.forward(30)
t.penup()
t.goto(40,80)
t.pendown()
t.color("red")
for  i in range(180):
		t.forward(0.7)
		t.right(1)